version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  machine:
    timezone: Australia/Melbourne
    node:
      version: 8.1.4
  dependencies:
    override:
      - npm update
      - npm install
  test:
    override:
      - npm test
  deployment:
    staging:
      branch: master
      heroku:
        appname: watch-pluto
